version: 2.1

orbs:
  rok8s-scripts: fairwinds/rok8s-scripts@11

executors:
  golang-exec:
    docker:
      - image: circleci/golang:1.14-stretch

references:
  install_goreleaser: &install_goreleaser
    run:
      name: Install GoReleaser
      command: |
        curl -fsSLo goreleaser.deb https://github.com/goreleaser/goreleaser/releases/download/v0.131.1/goreleaser_amd64.deb
        echo "640790dcbfa864f26de4c26c2d491f293a64525c8c6641c5bbdec7136b38977e goreleaser.deb" | sha256sum -c -
        sudo dpkg -i goreleaser.deb
        rm goreleaser.deb
jobs:
  test:
    working_directory: /go/src/github.com/fairwindsops/agones-allocator-client

    docker:
      - image: circleci/golang:1.14
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download && go mod verify
      - run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

  release_binary:
    working_directory: /go/src/github.com/fairwindsops/agones-allocator-client
    docker:
      - image: circleci/golang:1.14
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download && go mod verify
      - *install_goreleaser
      - run: goreleaser

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
  release:
    jobs:
      - release_binary:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
